### ISSUE TITLE
Allows uploads

### ISSUE THREAD

**Issue by gedw99** [nicokaiser/hugo-theme-gallery#15]
Your gallery is a truly polished mate ! It's so impressive how smooth it is.

Your going to like this i think:

https://github.com/acaloiaro/hugo-htmx-go-template

Its allows you to make Hugo interactive in to that you can make Forms, Upload Images, etc etc 

If you want to team up to make your gallery stuff do this let me know.

**Comment by nicokaiser** [comment]
Thanks for your suggestion. I think this is a different scope, this theme should stay, well, a theme. Users can still build their site with this theme and use htmx for pages, additional templates, etc.
But this theme should stay as simple as possible.
