### ISSUE TITLE
Font customization

### ISSUE THREAD

**Issue by mrubli** [nicokaiser/hugo-theme-gallery#17]
This is half question, half feature request. I was trying to change the font but that turned out to be a lot more difficult than I thought.

The font is hardcoded both in `site_head.html` and in `tailwind.config.js`. So I ended up doing something inspired by these two articles [[1](https://discourse.gohugo.io/t/font-selection-in-theme/8803/16)] [[2](https://www.banjocode.com/post/hugo/custom-css)]. I cloned `site_head.html` into my project and changed it as follows:

```diff
diff --git a/layouts/partials/site_head.html b/layouts/partials/site_head.html
index a76283f..d24df40 100644
--- a/layouts/partials/site_head.html
+++ b/layouts/partials/site_head.html
@@ -10,7 +10,13 @@
   <link rel="icon" type="image/svg+xml" href="{{ "images/favicon.svg" | relURL }}" />
   <link rel="icon" type="image/png" href="{{ "images/favicon.png" | relURL }}" />
   <link rel="apple-touch-icon" sizes="180x180" href="{{ "images/apple-touch-icon.png" | relURL }}" />
-  <link rel="preload" href="/fonts/Inter-roman.var.woff2" as="font" type="font/woff2" />
+  {{ if .Site.Params.customFonts -}}
+    {{ range .Site.Params.customFonts -}}
+    <link rel="preload" href="{{ . | relURL }}" as="font" type="font/woff2" />
+    {{- end -}}
+  {{- else -}}
+    <link rel="preload" href="/fonts/Inter-roman.var.woff2" as="font" type="font/woff2" />
+  {{- end }}
   <meta name="description" content="{{ with .Description }}{{ . }}{{ else }}{{ with .Site.Params.description }}{{ . }}{{ end }}{{ end }}" />
   {{ hugo.Generator }}
   {{ if .Params.private }}
@@ -22,6 +28,11 @@
   {{ partial "opengraph.html" . }}
   {{ $css := resources.Get "/css/styles.css" | resources.PostCSS (dict "inlineImports" true) | resources.Minify | resources.Fingerprint }}
   <link rel="stylesheet" href="{{ $css.RelPermalink }}" />
+  {{ if .Site.Params.customCSS -}}
+    {{ range .Site.Params.customCSS -}}
+    <link rel="stylesheet" href="{{ . | relURL }}" />
+    {{- end }}
+  {{- end }}
   {{ $js := resources.Get "js/main.js" | js.Build (dict "minify" true) | resources.Fingerprint }}
   <script src="{{ $js.RelPermalink }}" defer></script>
 </head>
```

That allowed me to add a custom CSS …

```css
@font-face {
  font-family: "Switzera";
  font-weight: 100 900;
  src: url("../fonts/switzera-regular.woff2") format("woff2");
}

html {
  font-family: "Switzera";
}
```

… and enable it and a custom font in my `hugo.yaml`:

```yaml
params:
  defaultTheme: dark
  customCSS:
  - css/custom.css
  customFonts:
  - fonts/switzera-regular.woff2
```

This works but it's not terribly elegant and there are still traces left of the original Inter font despite it not being used.

I haven't delved into TailwindCSS yet and maybe there's some magic to be performed there. But is there a better way to do things? Perhaps something could be added to the theme to make changing fonts the easy task it should be?

PS: This particular issue aside, I love the theme and it was amazingly easy to get great-looking results with little effort. So thanks a lot for your work!

**Comment by nicokaiser** [comment]
I think adding customization parameters would bloat the theme too much, this is why it is very opinionated ;-) (But this makes it easy to extend or modify)

- Copy the font files to `./static/fonts`. I found the OTF versions on fontlibrary.org, so for my test this would be something like this:

```
./static/fonts/SwitzeraADFRegular.woff2
./static/fonts/SwitzeraADFDemiBold.woff2
```

- Copy the theme's `assets/css/styles.css` to your `/assets/css/styles.css` and motify the `@font-face` directives:

```
./assets/css/styles.css:

@font-face {
  font-family: "Switzera";
  src: url("../fonts/SwitzeraADFRegular.otf")
    format("opentype");
  font-weight: normal;
  font-style: normal;
}

@font-face {
  font-family: "Switzera";
  src: url("../fonts/SwitzeraADFDemiBold.otf")
    format("opentype");
  font-weight: bold;
  font-style: normal;
}

@tailwind base;
@tailwind components;
@tailwind utilities;
...
```

- Copy the theme's `tailwind.config.js` to your site root, and change the `Inter var` to `Switzera` so Tailwind CSS will use the Switzera font.

- Copy the theme's `site_head.html` to your `./layouts/partials/site_head.html` and change the `preload` paths:

```
...
<link rel="preload" href="/fonts/SwitzeraADFRegular.woff2" as="font" type="font/woff2" />
<link rel="preload" href="/fonts/SwitzeraADFDemiBold.woff2" as="font" type="font/woff2" />
...
```

That should be pretty much it.

**Comment by mrubli** [comment]
Thanks! Your solution works well. I wouldn't say the duplication of the Tailwind CSS config and the theme's CSS file makes it particularly elegant, but I understand the desire to keep bloat minimal. It's always a trade-off between adding features on the "library" side and duplicating functionality on the "consumer" side, though, and often the theme authors are in a better position (architecture, expertise) to do so. Anyway, themes deserve to be opinionated and I respect that. :-)

It might be nice to have a section in the README.md with "non-features", i.e. features that are purposely not part of the theme but have a solution in the issue section, similar to the _Folders with no images_ section.

One last thing: I noticed that the dev tools console reports an error, even on the official example website:

> preload for 'https://hugo-gallery-example.netlify.app/fonts/Inter-roman.var.woff2' is found, but is not used because the request credentials mode does not match. Consider taking a look at crossorigin attribute.

Adding a `crossorigin="anonymous"` attribute to the font preload did the trick for me:

```
<link rel="preload" href="/fonts/Inter-roman.var.woff2" as="font" type="font/woff2" crossorigin="anonymous" />
```

There's some detail [here](https://github.com/w3c/preload/issues/32).
