### ISSUE TITLE
Vertical images automatically rotated

### ISSUE THREAD

**Issue by mpostument** [nicokaiser/hugo-theme-gallery#20]
Hello, i am trying to setup website. But i have many vertical images. And they getting rotated every time. Is there a way to disable automatic rotation 

![Screenshot 2023-11-06 at 13 01 03](https://github.com/nicokaiser/hugo-theme-gallery/assets/9252594/0a89156e-ed86-4435-980b-1c0894c9203e)

**Comment by nicokaiser** [comment]
The theme handles rotation like it is saved in the "orientation" EXIF tags: https://github.com/nicokaiser/hugo-theme-gallery/blob/dda83dccfbbd7b6ab71e2e6903ca4aa0d53c3d93/layouts/partials/page_gallery.html#L20C68-L20C76

So maybe your pictures were rotated in some way that the EXIF tag was not updated so it might get rotated twice (or never)?

You can create a local `layouts/partial/page_albums.html` and remove all `$rotation` handling from there. But it might be better to fix the images...
