### ISSUE TITLE
Image URL links

### ISSUE THREAD

**Issue by oulh** [nicokaiser/hugo-theme-gallery#22]
This album theme is great, it would be even better if it supports web image URL links.

**Comment by nicokaiser** [comment]
What do you mean by web image URL links?

**Comment by oulh** [comment]
> What do you mean by web image URL links?

photos from cloud storage, such as Amazon S3, Cloudflare R2

**Comment by nicokaiser** [comment]
Sorry, this is outside of the scope of this theme. This theme heavily depends on Hugo's image processing functions, which only work when images are stored locally within the Hugo site.

Hosting image outside of the site (whether or not including resized variants of them!) may require a different approach.
