### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by oschwand** [nicokaiser/hugo-theme-gallery#23]
Hello, installation instructions are not accurate enough, I was a bit lost since a lot of manual steps are needed.

I had to copy the following files:
- package.hugo.json
- package.json package-lock.json
- hugo.toml

And then run:
- `npm install`

For some reason, `hugo mod init` was not working and I had to rely on the good old `go mod init`.

I may submit a pull request in the future to upgrade the README but my understanding of all that is not good enough and I have no time for experiments right now.

Thanks

**Comment by nicokaiser** [comment]
Actually the "correct" (although rather cumbersome) process for initializing a project with a theme module is this:

    $ hugo mod init github.com/<your_user>/<your_project> # Initialize project

Add [`hugo.toml`](https://github.com/nicokaiser/hugo-theme-gallery/blob/main/exampleSite/hugo.toml) with `theme = "github.com/nicokaiser/hugo-theme-gallery"`

Then install the theme and its dependencies:

    $ hugo mod get # Install the theme
    $ hugo mod npm pack # Initialize package.json
    $ npm i # Install dependencies (Tailwind CSS, etc.)

**Comment by nicokaiser** [comment]
I know this is not very convenient, since you need to execute these steps in that very order, and need Go and Node.js installed. I'll try to release a version of this theme which only requires the Hugo binary (and thus will not be customizable at all of course).

**Comment by Juniors017** [comment]
hi 

i have same problem. I don't understand this installation :s

**Comment by nicokaiser** [comment]
Did you try the instructions in my comment above?

**Comment by nicokaiser** [comment]
What did these commands do instead? Can you provide an error message or something?

**Comment by oschwand** [comment]
Indeed, some parts still seems to be missing when I follow the exact instructions you provided
````
$ hugo                                                                                       0s
Start building sites … 
hugo v0.120.4+extended linux/amd64 BuildDate=2023-11-30T21:09:44Z VendorInfo=debian:0.120.4-1

WARN  found no layout file for "html" for kind "home": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN  found no layout file for "html" for kind "taxonomy": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
````

**Comment by oschwand** [comment]
In short, nearly nothing happens
```
~/tmp/toto$ hugo mod get
~/tmp/toto$ hugo mod npm pack
~/tmp/toto$ npm i
up to date, audited 1 package in 37ms

found 0 vulnerabilities
~/tmp/toto$ ls
go.mod  package.hugo.json  package.json  package-lock.json
````

**Comment by oschwand** [comment]
Ok, my bad. I forgot to add the thme line in the hugo.toml file...

**Comment by oschwand** [comment]
Still, the result is disappointing:
![2023-12-08-143752_299x147_scrot](https://github.com/nicokaiser/hugo-theme-gallery/assets/120162/24b1e592-d2e6-4fae-927e-cb87b4d9ce26)

**Comment by nicokaiser** [comment]
0. Make sure you have installed Node.js >= 18, Go and Hugo
1. Initialize your project with `hugo mod init yourdomain.com`
2. Add `hugo.toml` [from here](https://github.com/nicokaiser/hugo-theme-gallery/blob/main/exampleSite/hugo.toml) and modify it
3. Execute `hugo mod get`
4. Execute `hugo mod npm pack`
5. Execute `npm install`

**Comment by oschwand** [comment]
Ok, so the key was to have a full hugo.toml and not a minimal one: it works now !

The point of my issue was to ask for precise instructions which may be put in the README: I guess we are.

**Comment by Juniors017** [comment]
hi
i replay installation and i have this result when i run hugo server: 
```
`
hugo: downloading modules …
hugo: collected modules in 10004 ms
Watching for changes in C:\Users\valen\Documents\Dev_site\test\monsite\{archetypes,assets,content,data,hugo_stats.json,i18n,layouts,package.hugo.json,package.json,static}
Watching for config changes in C:\Users\valen\Documents\Dev_site\test\monsite\hugo.toml, C:\Users\valen\Documents\Dev_site\test\monsite\go.mod
Start building sites … 
hugo v0.121.0-e321c3502aa8e80a7a7c951359339a985f082757+extended windows/amd64 BuildDate=2023-12-05T15:22:31Z VendorInfo=gohugoio


                   | EN  
-------------------+-----
  Pages            | 12
  Paginator pages  |  0
  Non-page files   |  0
  Static files     |  4
  Processed images |  0
  Aliases          |  0
  Sitemaps         |  1
  Cleaned          |  0

Built in 7304 ms
Environment: "development"
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
```
`
home page work but other don't work normaly

**Comment by nicokaiser** [comment]
What does „don’t work“ mean? It is hard to find the cause of a problem when I either don’t know what you did, or what was the outcome.

Did the home page look good after the installation? Can you try to make the example site work and start work from there instead of starting a new project?

**Comment by harrythezomby** [comment]
> 0. Make sure you have installed Node.js >= 18, Go and Hugo
> 1. Initialize your project with `hugo mod init yourdomain.com`
> 2. Add `hugo.toml` [from here](https://github.com/nicokaiser/hugo-theme-gallery/blob/main/exampleSite/hugo.toml) and modify it (its `build` and `write_stats` settings are important for Tailwind to work correctly)
> 3. Execute `hugo mod get`
> 4. Execute `hugo mod npm pack`
> 5. Execute `npm install`

Thanks for these instructions! They worked for me and the site looks the way it should. Just one thing however, I had to change my go version from 1.21.3 or something to 1.20, since I was getting a version unsupported error when trying to `hugo mod get`.

**Comment by nicokaiser** [comment]
Please try the new version. I updated this theme to include the already compiled CSS, so neither Go nor Node.js are required now.

**Comment by fedelibre** [comment]
I'm using hugo modules for the first time. `hugo mod get` should download the theme in the `themes` directory, right? Well, it's not working for me.

I've copied the hugo.toml from the example site, as suggested above.

```
$ go version
go version go1.21.5 linux/amd64

$ hugo version
hugo v0.121.1-00b46fed8e47f7bb0a85d7cfc2d9f1356379b740 linux/amd64 BuildDate=2023-12-08T08:47:45Z VendorInfo=gohugoio

$ hugo mod get
go: no module dependencies to download
go: downloading github.com/nicokaiser/hugo-theme-gallery/v2 v2.1.1
go: added github.com/nicokaiser/hugo-theme-gallery/v2 v2.1.1
hugo: collected modules in 1213 ms

$ tree .
.
├── archetypes
│   └── default.md
├── assets
├── content
├── data
├── go.mod
├── go.sum
├── hugo.toml
├── i18n
├── layouts
├── static
└── themes
```

What I'm doing wrong?

**Comment by nicokaiser** [comment]
> `hugo mod get` should download the theme in the `themes` directory, right?

No, `hugo mod get` downloads the theme to your local Go module cache. It is not copied to your site, but you can use the theme, e.g. with `hugo`.

If you want a copy of the theme in your `themes` directory, you need to download the Git repository and copy it there by hand.

**Comment by fedelibre** [comment]
> I'm using hugo modules for the first time. `hugo mod get` should download the theme in the `themes` directory, right?

Sorry, wrong assumption. I've launched 'hugo server` and it works. I have to search for a tutorial about Hugo modules, as the documentation doesn't explain them well.

@nicokaiser The README still doesn't contain the instructions to download the theme as a hugo module. I think you should write to first copy the hugo.toml file from Github, then run `hugo mod get`.

**Comment by nicokaiser** [comment]
> I think you should write to first copy the hugo.toml file from Github, then run `hugo mod get`

Adding `theme = ["github.com/nicokaiser/hugo-theme-gallery/v2"]` to your `hugo.toml` and then running `hugo` to build the site should be enough as of v2 of this theme.
