### ISSUE TITLE
Unable to build the site on Cloudfare

### ISSUE THREAD

**Issue by bhdicaire** [nicokaiser/hugo-theme-gallery#34]
I can't use use Cloudflare CI/CD to build the site although I can build it locally on my Mac.

I got an an error calling partial: partial "page_gallery.html" timed out after 30s, I don't have any local layouts.

==============================================================
17:20:08.018 | Cloning repository...
17:20:10.723 | From https://github.com/...
17:20:10.724 | * branch            ef752e31fe38a13dc21619547eea0596fe5ff256 -> FETCH_HEAD
17:20:10.724 |  
17:20:11.122 | HEAD is now at ef752e3 Add vendor in the theme by running hugo mod vendor
17:20:11.214 | Using v2 root directory strategy
17:20:11.245 | Success: Finished cloning repository files
17:20:12.095 | Detected the following tools from environment:
17:20:12.096 | Executing user command: hugo --gc --minify
17:20:12.396 | Start building sites …
17:20:12.397 | hugo v0.118.2-da7983ac4b94d97d776d7c2405040de97e95c03d+extended linux/amd64 BuildDate=2023-08-31T11:23:51Z VendorInfo=gohugoio
17:20:42.497 | ERROR render of "page" failed: "/opt/buildhome/repo/_vendor/github.com/nicokaiser/hugo-theme-gallery/v2/layouts/_default/single.html:3:6": execute of template failed: template: _default/single.html:3:6: executing "main" at <partial "page_gallery.html" .>: error calling partial: partial "page_gallery.html" timed out after 30s. This is most likely due to infinite recursion. If this is just a slow template, you can try to increase the 'timeout' config setting.
17:20:42.497 | Total in 30106 ms
17:20:42.498 | Error: error building site: render: failed to render pages: render of "page" failed: "/opt/buildhome/repo/_vendor/github.com/nicokaiser/hugo-theme-gallery/v2/layouts/_default/single.html:3:6": execute of template failed: template: _default/single.html:3:6: executing "main" at <partial "page_gallery.html" .>: error calling partial: partial "page_gallery.html" timed out after 30s. This is most likely due to infinite recursion. If this is just a slow template, you can try to increase the 'timeout' config setting.
17:20:42.511 | Failed: Error while executing user command. Exited with error code: 1
17:20:42.518 | Failed: build command exited with code: 1
17:20:43.538 | Failed: error occurred while running build command

**Comment by bhdicaire** [comment]
I figure it out, I had to augment the time out from 30 seconds to 120 seconds in my config.yml:
`timeout: 120s`

**Comment by CallMeL** [comment]
> I figure it out, I had to augment the time out from 30 seconds to 120 seconds in my config.yml: `timeout: 120s`

hi @bhdicaire, I have the same time out issue while deploying,  but I didn't find the config.yml file, is it the same with hugo.toml?
Thank you!

**Comment by nicokaiser** [comment]
Yes, `hugo.toml`, or `config/_default/hugo.toml` is where configuration is stored. `config.toml` or `config.yml` are the same, though these may get deprecated.
