### ISSUE TITLE
Adding an image to the about page

### ISSUE THREAD

**Issue by inezpereira** [nicokaiser/hugo-theme-gallery#36]
Hello there @nicokaiser !

First of all, thank you very much for creating this theme!
I've just gotten started, and am having some trouble getting an image onto my about.md page.

I see you don' allow images in posts. Does that also apply to the about page?

Thank you!

**Comment by nicokaiser** [comment]
Bom dia @inezpereira!
The theme is not really made for content other than galleries of images. However you can create posts (like the about page) and include images there – although these images need to be in your static folder (like `/static/images/me.jpg`). Then you can include them with something like

```md
![Me](/images/me.jpg)
```

Unfortunately images cannot be alongside the posts ("page bundles"), otherwise these pages get rendered as galleries, which might not be what you want.

**Comment by inezpereira** [comment]
Bom dia, bom dia! 😊

I understand!

I was trying the solution you sent me (see screenshots below), but I can't get it to work.

What the screenshots show:
1. The line added to the about.md file
2. The actual path to the image
3. The result after running `hugo server`

<img width="713" alt="image" src="https://github.com/nicokaiser/hugo-theme-gallery/assets/20027814/b2b6fe0b-d404-4ecd-afd8-0e4b59d55349">

<img width="737" alt="image" src="https://github.com/nicokaiser/hugo-theme-gallery/assets/20027814/ccf5f971-6a14-4599-b440-8fa2435609d8">

<img width="942" alt="image" src="https://github.com/nicokaiser/hugo-theme-gallery/assets/20027814/92ded206-dddd-4173-8a7f-f22577cc71a8">

I have tried:
- checking the path
- typing relative paths (`../static/images/me.png`)
- trying again after converting the image to JPEG

Hm, what am I missing?

**Comment by nicokaiser** [comment]
Could you try

```md
![Me](/images/me.jpg)
```

(without the `/static`) in the Markdown? `/static` is being stripped when building the site.

**Comment by ethicalsnacker** [comment]
I have suffering the same, 

I have run with jpg, png. 

Tried this in /public/images
Tried this in the same folder alongside my .md

The image is viewed fine in the Markdown viewer in VSCode so would suggest a correct path.

**Comment by nicokaiser** [comment]
No, the Markdown viewer in VSCode will reference the wrong location. Images need to go in the `/static` folder, e.g. `/static/images/foo.jpg` and need to be referenced without the `/static` prefix, e.g. `![description](/images/foo.jpg`.

**Comment by inezpereira** [comment]
It works! Thank you @nicokaiser ! :D

**Comment by inezpereira** [comment]
It works! Thank you @nicokaiser ! :D
