### ISSUE TITLE
How to change home page welcome text and description

### ISSUE THREAD

**Issue by Shbu** [nicokaiser/hugo-theme-gallery#38]
Hi @nicokaiser 
Thank you so much for the excellent gallery theme. Really liking it!

I was wondering, in the hugo.toml file, I see we have 'title' value that applies to the website name, which is in the left top corner of the page. There is also 'title' under params, I assume this is for home page title, center of the page. How do I edit just the welcome title and add a description to it? Below code doesn't seem to be working for me. The main website title applies to both areas. Description doesn't show up at all. Could you help, thanks.

![image](https://github.com/nicokaiser/hugo-theme-gallery/assets/5582253/0487dd30-3f00-46d5-96e8-6798d77e114f)

`title = "Website"
languageCode = "en"
disableKinds = ["taxonomy", "term"]
defaultContentLanguage = "en"
enableRobotsTXT = true

[params]
  title = "Gallery"
  description = "Example site for hugo-theme-gallery"`

**Comment by nicokaiser** [comment]
Hello @Shbu! Thank you, glad you like the theme!
You can adjust the text on the homepage in the [`content/_index.md`](https://github.com/nicokaiser/hugo-theme-gallery/blob/9db24cdd3a7643e1a643d5a8ffa582164b8aca4a/exampleSite/content/_index.md?plain=1#L2) file.

**Comment by Shbu** [comment]
Thank you very much! It worked.
