### ISSUE TITLE
Inconsistency in photo count in albums in example site

### ISSUE THREAD

**Issue by hugo-sid** [nicokaiser/hugo-theme-gallery#53]
First, thanks for this great theme.

I just found a small bug/error in photo count in the example site.

## Steps to reproduce

1. Navigate to https://nicokaiser.github.io/hugo-theme-gallery/

    You will see that the 'Animals' album has 14 photos.
    
    ![image](https://github.com/nicokaiser/hugo-theme-gallery/assets/122173059/a6ff0a2a-6611-4bd8-9d88-b691bfea2f37)

2. Navigate to https://nicokaiser.github.io/hugo-theme-gallery/animals/

    You will see that there are 13 (=9+4) photos inside.
    
    ![image](https://github.com/nicokaiser/hugo-theme-gallery/assets/122173059/7773bfc5-3fd7-49b5-a7af-957ec13c3b91)

**Comment by nicokaiser** [comment]
I completely agree! 
From a technical point of view, the count of 14 is correct (because the 14th photo is the one of the brown cameleon, which is the cover photo of the "Animals" album), but since this is not a photo you can view on its own, it should not be counted.
