### ISSUE TITLE
"Page not found" when building

### ISSUE THREAD

**Issue by realdeadbeef** [nicokaiser/hugo-theme-gallery#65]
I have tried copying the exampleSite, that doesn't work.

My steps are:  

- `hugo new site tomtakesphotos.com`
- `cd tomtakesphotos.com`
- `git init`
- `git submodule add --depth=1 https://github.com/nicokaiser/hugo-theme-gallery.git themes/gallery`
- Add the line `theme = 'gallery` to `hugo.toml`
- `hugo server`

```
Start building sites … 
hugo v0.111.3+extended linux/amd64 BuildDate=2023-03-16T08:41:31Z VendorInfo=debian:0.111.3-1
WARN 2024/05/25 09:56:27 found no layout file for "HTML" for kind "home": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2024/05/25 09:56:27 found no layout file for "HTML" for kind "taxonomy": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2024/05/25 09:56:27 found no layout file for "HTML" for kind "taxonomy": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.

                   | EN  
-------------------+-----
  Pages            |  3  
  Paginator pages  |  0  
  Non-page files   |  0  
  Static files     |  0  
  Processed images |  0  
  Aliases          |  0  
  Sitemaps         |  1  
  Cleaned          |  0  

Built in 4 ms
Watching for changes in /home/tom/Documents/tomtakesphotos.com/{archetypes,assets,content,data,layouts,static}
Watching for config changes in /home/tom/Documents/tomtakesphotos.com/config.toml, /home/tom/Documents/tomtakesphotos.com/go.mod
Environment: "development"
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop
```

Creates:  
![image](https://github.com/nicokaiser/hugo-theme-gallery/assets/64917571/631f7039-d38c-4f9f-8cf2-6586d49f6425)

**Comment by nicokaiser** [comment]
Could you try with a newer Hugo version? I am not sure if this solves this particular problem, but the theme requires Hugo >= 0.121.

**Comment by notsungod** [comment]
Hey man! You have to build the html source code in public directory with the simple `hugo` command.

> I have tried copying the exampleSite, that doesn't work.
> 
> My steps are:
> 
>     * `hugo new site tomtakesphotos.com`
> 
>     * `cd tomtakesphotos.com`
> 
>     * `git init`
> 
>     * `git submodule add --depth=1 https://github.com/nicokaiser/hugo-theme-gallery.git themes/gallery`
> 
>     * Add the line `theme = 'gallery` to `hugo.toml`
> 
>     * `hugo server`
> 
> 
> ```
> Start building sites … 
> hugo v0.111.3+extended linux/amd64 BuildDate=2023-03-16T08:41:31Z VendorInfo=debian:0.111.3-1
> WARN 2024/05/25 09:56:27 found no layout file for "HTML" for kind "home": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
> WARN 2024/05/25 09:56:27 found no layout file for "HTML" for kind "taxonomy": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
> WARN 2024/05/25 09:56:27 found no layout file for "HTML" for kind "taxonomy": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
> 
>                    | EN  
> -------------------+-----
>   Pages            |  3  
>   Paginator pages  |  0  
>   Non-page files   |  0  
>   Static files     |  0  
>   Processed images |  0  
>   Aliases          |  0  
>   Sitemaps         |  1  
>   Cleaned          |  0  
> 
> Built in 4 ms
> Watching for changes in /home/tom/Documents/tomtakesphotos.com/{archetypes,assets,content,data,layouts,static}
> Watching for config changes in /home/tom/Documents/tomtakesphotos.com/config.toml, /home/tom/Documents/tomtakesphotos.com/go.mod
> Environment: "development"
> Serving pages from memory
> Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
> Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
> Press Ctrl+C to stop
> ```
> 
> Creates: ![image](https://private-user-images.githubusercontent.com/64917571/333785441-631f7039-d38c-4f9f-8cf2-6586d49f6425.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4NzQzNzIsIm5iZiI6MTcxOTg3NDA3MiwicGF0aCI6Ii82NDkxNzU3MS8zMzM3ODU0NDEtNjMxZjcwMzktZDM4Yy00ZjlmLThjZjItNjU4NmQ0OWY2NDI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDIyNDc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkNmExYzFhNDBiM2UyOTFiZWYzMTg4ZjA3MmU4MTI2OWIzNWM5Mzk3ZjE3YWFkNDk3NDFiNGIzMzg0N2Q0ZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-f2omfD0qnh03DsvL2KbEi7s_gHYEfsz7EzfED9rrYc)

**Comment by realdeadbeef** [comment]
Can I reopen this, I've tried again, it still doesn't work, I'm on the latest version of hugo.
