### ISSUE TITLE
Adding gallery to homepage 

### ISSUE THREAD

**Issue by hjklpt1** [nicokaiser/hugo-theme-gallery#69]
Is it possible to add whole gallery grid images to the homepage?  I do not want to create albums. Thanks in advance for your suggestions.

**Comment by nicokaiser** [comment]
Did you try to just create an `_index.md` file? Of course there cannot be sub-albums then, but that might work…

**Comment by hjklpt1** [comment]
I have a folder in \content\paintings and I have the \content\_index.md file. However it does not add the photos under the paintings to the home page like a single page gallery (masonry grid style like in the cats example page). 

I tried to edit home.html layout with {{ partial "gallery.html" . }} I don't want to intervene with the original layouts but it is the only solution I could find.

**Comment by nicokaiser** [comment]
Oh you are right. You might need to add a local version of home.html which looks like single.html. Then you can use `content/_index.md` and your images go to `content/*.jpg`.

**Comment by nicokaiser** [comment]
Ok, so here is how it's done:

- Install the theme like described in the README
- Create a `layout/_default/home.html` in your site which contains the following:

```
{{ define "main" }}
  {{ partial "title.html" . }}
  {{ partial "gallery.html" . }}
  {{ partial "related.html" . }}
{{ end }}
```

- Create `content/index.md` (with no underscore!) like you would in a regular gallery:

```markdown
```

**Comment by juan11iguel** [comment]
I think it would be a good idea to compile all of these questions in the README, maybe as a FAQ so they are more discoverable. If I have time I would try to do it myself and do a PR
