### ISSUE TITLE
Changes to hugo.toml not reflected after restarting Hugo server

### ISSUE THREAD

**Issue by eskopp** [nicokaiser/hugo-theme-gallery#71]
I created my repo as you described in #70. When I close the Hugo server, I make changes to hugo.toml. Let's say changing the heading and then running hugo server again, no change is shown and the example page is loaded again. What am I doing wrong? Thanks for your help

**Comment by nicokaiser** [comment]
Sorry, I have no idea what you are doing.
I created a new directory with only these two files:

go.mod:

```
module example.com

go 1.20

require github.com/nicokaiser/hugo-theme-gallery/v4 v4.1.11 // indirect
```

hugo.toml:

```
title = "My Gallery"
[module]
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery/v4"
```

Then, when running `hugo server` you can access the (empty) gallery on http://localhost:1313/. When making changes to `hugo.toml` these are reflected immediately without needing to restart.
