### ISSUE TITLE
Images doesn't show up on albums

### ISSUE THREAD

**Issue by guinslym** [nicokaiser/hugo-theme-gallery#75]
https://github.com/guinslym/CPLS-Gallery

On my albums - See Chalklines - I can't see images. But on Animals I can see images on Dogs and Cats. Do you have any hints?

**Comment by guinslym** [comment]
My index file was not properly. name

**Comment by nicokaiser** [comment]
I just saw that you are using an old version of the theme. I'll create a PR on your site!
