### ISSUE TITLE
Changing sort_order to Date has no effect

### ISSUE THREAD

**Issue by timcappalli** [nicokaiser/hugo-theme-gallery#81]
I've tested this on both my site and the sample site, and switching `sort_order` to `Date` has no effect. 

All of my images have EXIF Create Times and I even added some random values to the Cat images in your sample site.

Is `sort_by` `Date` (Exif.Date) known to be working?

**Comment by nicokaiser** [comment]
Nice catch! Sorry I seem to have broken the `Date` sorting while refactoring the gallery view. Could you try again with the current version (4.2.3) of the theme?

**Comment by timcappalli** [comment]
That worked. Thank you @nicokaiser!
