### ISSUE TITLE
Add possibilities to resize photos

### ISSUE THREAD

**Issue by 22decembre** [nicokaiser/hugo-theme-gallery#84]
There should be ways to resize images when processing them. Hugo has apparently great image processing capabilities.

When copying pictures to the "public" folder, we should use that step to process them according to parameters from the config.toml.

**Comment by nicokaiser** [comment]
This theme does resize the images in the `contents` folder. Files in `public` are kept as-is, since these are meant not to be processed (and cannot be processed by Hugo I guess).
